require("me.packer")
require("me.remap")
require("me.telescope")
require("me.fugitive")
require("me.harpoon")
require("me.treesitter")
require("me.undotree")
require("me.lazygit")
require("me.lsp")
require("me.oil-config")
require("me.blackjack")
require("me.color-picker-config")
require("me.trouble-config")
require("me.neodev-config")
vim.cmd[[colorscheme tokyonight]]
