require("me.remap")
require("me.telescope")
require("me.fugitive")
require("me.harpoon")
require("me.treesitter")
require("me.undotree")
require("me.lazygit")
require("me.packer")
require("me.lsp")
require("me.oil")
vim.cmd[[colorscheme tokyonight]]
